import Image from "next/image";
import Logo from "../../public/logo.js";
import Hero from "./components/Hero.jsx";
import Navbar from "./components/Navbar.jsx";
import type { Metadata } from "next";
import IconCard from "./components/IconCard.jsx";
import editor from "/editor.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center">
      <Navbar />
      <Hero
        video="/network-vid-white-2.mp4"
        title="Company Name"
        heading="Put a Headline Here"
        subheading="Put a Subheading Here"
        description="Dorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus elit sed risus."
        cta={{ text: "Get Started", link: "/" }}
      />
      <div className="bg-dark flex flex-col lg:flex-row justify-center items-center lg:justify-around w-full h-1/2 py-24 px-60">
        <IconCard
          icon={
            <span className="material-symbols-outlined text-7xl ">
              network_node
            </span>
          }
          description="Borem ipsum"
          textColor="text-white"
          iconColor="text-white"
          cta={{ text: "Learn more", link: "/" }}
        />
        <IconCard
          icon={
            <span className="material-symbols-outlined text-7xl ">
              handshake
            </span>
          }
          description="Borem ipsum dolor sit amet"
          textColor="text-white"
          iconColor="text-white"
          cta={{ text: "Learn More", link: "/" }}
        />
        <IconCard
          icon={
            <span className="material-symbols-outlined text-7xl ">
              database
            </span>
          }
          description="Lorem ipsum dolor sit amet"
          textColor="text-white"
          iconColor="text-white"
          cta={{ text: "Learn More", link: "/" }}
        />
        <IconCard
          icon={
            <span className="material-symbols-outlined text-7xl ">
              folder_data
            </span>
          }
          description="Dorem ipsum dolor sit amet, consectetur adipiscing elit"
          textColor="text-white"
          iconColor="text-white"
          cta={{ text: "Learn More", link: "/" }}
        />
      </div>
      <div className="flex w-full py-48 px-60 justify-center">
        <div className="w-1/3 m-5">
          <h1 className="text-5xl">An Interesting Header About A Topic</h1>
          <p>
            Borem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu
            turpis molestie, dictum est a, mattis tellus. Sed dignissim, metus
            nec fringilla accumsan, risus sem sollicitudin lacus, ut interdum
            tellus elit sed risus. Maecenas eget condimentum velit, sit amet
            feugiat lectus.
          </p>
          <br />
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>
        <div className="w-11/12">
          <img src="/editor.png" />
        </div>
      </div>
      {/* <div className="absolute -z-10 top-11/12 bg-gradient-to-b from-slateGreen to-muddyGreen h-screen 6 w-full max-w-full overflow-hidden"></div> */}
      <div className="flex w-full py-48 px-60 justify-center border-2">
        <div className="h-96 rounded-lg">
          <img
            className="rounded-xl"
            src="/alina-grubnyak-R84Oy89aNKs-unsplash - Photo by Alina Grubnyaka on Unsplash.jpg"
          />
        </div>
        <div className="w-1/3 m-5">
          <h1 className="text-5xl">An Interesting Header About A Topic</h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla
            porttitor massa id neque aliquam vestibulum morbi blandit cursus.
            Nulla facilisi etiam dignissim diam quis enim lobortis. Arcu dictum
            varius duis at consectetur lorem donec. Vitae auctor eu augue ut
            lectus arcu bibendum at varius. Id velit ut tortor pretium viverra
            suspendisse potenti nullam ac. Sagittis eu volutpat odio facilisis
            mauris sit amet massa vitae.
          </p>
        </div>
      </div>
    </main>
  );
}
